from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils import timezone



class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100,default='')
    city = models.CharField(max_length=100,default='')
    website=models.URLField(max_length=100,default='')
    phone=models.IntegerField(default=0)

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile=UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)

class Clients(models.Model):
    id_c_l = models.AutoField(primary_key=True)
    nom_fr = models.CharField(max_length=200,default='',blank=True,null=True)
    adresse_fr=models.CharField(max_length=200,default='',blank=True,null=True)
    nom_an = models.CharField(max_length=200,default='',blank=True,null=True)
    adresse_an=models.CharField(max_length=200,default='',blank=True,null=True)
    nom_ar = models.CharField(max_length=200,default='',blank=True,null=True)
    adresse_ar=models.CharField(max_length=200,default='',blank=True,null=True)
    numero=models.CharField(max_length=200,default='',blank=True,null=True)
    email=models.EmailField(default='',blank=True)

class CompteBancaires(models.Model):
    id_c_b= models.AutoField(primary_key=True)
    num_b_fr = models.CharField(max_length=100,default='')
    num_b_an = models.CharField(max_length=100,default='')
    num_b_ar = models.CharField(max_length=100,default='')
    code_s_fr=models.CharField(max_length=100,default='')
    code_s_an=models.CharField(max_length=100,default='')
    code_s_ar=models.CharField(max_length=100,default='')
    adresse_b_fr = models.CharField(max_length=100,default='')
    adresse_b_an = models.CharField(max_length=100,default='')
    adresse_b_ar = models.CharField(max_length=100,default='')

class Produits(models.Model):
    id_c_p = models.AutoField(primary_key=True)
    designation_fr = models.CharField(max_length=100,default='')
    designation_an = models.CharField(max_length=100,default='')
    designation_ar =models.CharField(max_length=100,default='')
    prix_u_fr=models.FloatField(null=True)
    prix_u_an=models.FloatField(null=True)
    prix_u_ar=models.FloatField(null=True)

class FacturesProforma(models.Model):
    id_f = models.AutoField(primary_key=True)
    type=models.CharField(max_length=100,blank=True)
    prix_t=models.FloatField(null=True)
    prix_t_lettres_fr=models.CharField(max_length=100,blank=True)
    prix_t_lettres_an=models.CharField(max_length=100,blank=True)
    prix_t_lettres_ar=models.CharField(max_length=100,blank=True)
    unite=models.CharField(max_length=100,blank=True)
    destination =models.CharField(max_length=100,blank=True)
    mode_livraison =models.CharField(max_length=100,blank=True)
    port_chargement =models.CharField(max_length=100,blank=True)
    pays_origine =models.CharField(max_length=100,blank=True)
    nb_conteneur=models.CharField(max_length=100,blank=True)
    nb_colis=models.IntegerField(blank=True,null=True)
    poids_net=models.FloatField(null=True)
    poids_brut=models.FloatField(null=True)
    ngp =models.CharField(max_length=100,blank=True)
    mode_paiement =models.CharField(max_length=100,blank=True)
    id_c_b_f=models.ForeignKey(CompteBancaires,null=True,blank=True)
    id_c_f=models.ForeignKey(Clients,null=True,blank=True)
    date=models.DateField(default=timezone.now)
    code_date=models.CharField(max_length=100,blank=True)
    code=models.IntegerField(blank=True,null=True)
    o_t_fr=models.CharField(max_length=100,blank=True)
    o_c_fr=models.CharField(max_length=100,blank=True)
    o_t_an=models.CharField(max_length=100,blank=True)
    o_c_an=models.CharField(max_length=100,blank=True)
    o_t_ar=models.CharField(max_length=100,blank=True)
    o_c_ar=models.CharField(max_length=100,blank=True)
    os_t_fr=models.CharField(max_length=100,blank=True)
    os_c_fr=models.CharField(max_length=100,blank=True)
    os_t_an=models.CharField(max_length=100,blank=True)
    os_c_an=models.CharField(max_length=100,blank=True)
    os_t_ar=models.CharField(max_length=100,blank=True)
    os_c_ar=models.CharField(max_length=100,blank=True)
    ot_t_fr=models.CharField(max_length=100,blank=True)
    ot_c_fr=models.CharField(max_length=100,blank=True)
    ot_t_an=models.CharField(max_length=100,blank=True)
    ot_c_an=models.CharField(max_length=100,blank=True)
    ot_t_ar=models.CharField(max_length=100,blank=True)
    ot_c_ar=models.CharField(max_length=100,blank=True)

class FacturesEdex(models.Model):
    id_f = models.AutoField(primary_key=True)
    type=models.CharField(max_length=100,blank=True)
    prix_t=models.FloatField(null=True)
    prix_t_lettres_fr=models.CharField(max_length=100,blank=True)
    prix_t_lettres_an=models.CharField(max_length=100,blank=True)
    prix_t_lettres_ar=models.CharField(max_length=100,blank=True)
    unite=models.CharField(max_length=100,blank=True)
    destination =models.CharField(max_length=100,blank=True)
    mode_livraison =models.CharField(max_length=100,blank=True)
    port_chargement =models.CharField(max_length=100,blank=True)
    pays_origine =models.CharField(max_length=100,blank=True)
    nb_conteneur=models.CharField(max_length=100,blank=True)
    nb_colis=models.IntegerField(blank=True,null=True)
    poids_net=models.FloatField(null=True)
    poids_brut=models.FloatField(null=True)
    ngp =models.CharField(max_length=100,blank=True)
    mode_paiement =models.CharField(max_length=100,blank=True)
    id_c_b_f=models.ForeignKey(CompteBancaires,null=True,blank=True)
    id_c_f=models.ForeignKey(Clients,null=True,blank=True)
    date=models.DateField(default=timezone.now)
    code_date=models.CharField(max_length=100,blank=True)
    code=models.IntegerField(blank=True,null=True)
    o_t_fr=models.CharField(max_length=100,blank=True)
    o_c_fr=models.CharField(max_length=100,blank=True)
    o_t_an=models.CharField(max_length=100,blank=True)
    o_c_an=models.CharField(max_length=100,blank=True)
    o_t_ar=models.CharField(max_length=100,blank=True)
    o_c_ar=models.CharField(max_length=100,blank=True)
    os_t_fr=models.CharField(max_length=100,blank=True)
    os_c_fr=models.CharField(max_length=100,blank=True)
    os_t_an=models.CharField(max_length=100,blank=True)
    os_c_an=models.CharField(max_length=100,blank=True)
    os_t_ar=models.CharField(max_length=100,blank=True)
    os_c_ar=models.CharField(max_length=100,blank=True)
    ot_t_fr=models.CharField(max_length=100,blank=True)
    ot_c_fr=models.CharField(max_length=100,blank=True)
    ot_t_an=models.CharField(max_length=100,blank=True)
    ot_c_an=models.CharField(max_length=100,blank=True)
    ot_t_ar=models.CharField(max_length=100,blank=True)
    ot_c_ar=models.CharField(max_length=100,blank=True)

class FacturesUnpa(models.Model):
    id_f = models.AutoField(primary_key=True)
    type=models.CharField(max_length=100,blank=True)
    prix_t=models.FloatField(null=True)
    prix_t_lettres_fr=models.CharField(max_length=100,blank=True)
    prix_t_lettres_an=models.CharField(max_length=100,blank=True)
    prix_t_lettres_ar=models.CharField(max_length=100,blank=True)
    unite=models.CharField(max_length=100,blank=True)
    destination =models.CharField(max_length=100,blank=True)
    mode_livraison =models.CharField(max_length=100,blank=True)
    port_chargement =models.CharField(max_length=100,blank=True)
    pays_origine =models.CharField(max_length=100,blank=True)
    nb_conteneur=models.CharField(max_length=100,blank=True)
    nb_colis=models.IntegerField(blank=True,null=True)
    poids_net=models.FloatField(null=True)
    poids_brut=models.FloatField(null=True)
    ngp =models.CharField(max_length=100,blank=True)
    mode_paiement =models.CharField(max_length=100,blank=True)
    id_c_b_f=models.ForeignKey(CompteBancaires,null=True,blank=True)
    id_c_f=models.ForeignKey(Clients,null=True,blank=True)
    date=models.DateField(default=timezone.now)
    code_date=models.CharField(max_length=100,blank=True)
    code=models.IntegerField(blank=True,null=True)
    o_t_fr=models.CharField(max_length=100,blank=True)
    o_c_fr=models.CharField(max_length=100,blank=True)
    o_t_an=models.CharField(max_length=100,blank=True)
    o_c_an=models.CharField(max_length=100,blank=True)
    o_t_ar=models.CharField(max_length=100,blank=True)
    o_c_ar=models.CharField(max_length=100,blank=True)
    os_t_fr=models.CharField(max_length=100,blank=True)
    os_c_fr=models.CharField(max_length=100,blank=True)
    os_t_an=models.CharField(max_length=100,blank=True)
    os_c_an=models.CharField(max_length=100,blank=True)
    os_t_ar=models.CharField(max_length=100,blank=True)
    os_c_ar=models.CharField(max_length=100,blank=True)
    ot_t_fr=models.CharField(max_length=100,blank=True)
    ot_c_fr=models.CharField(max_length=100,blank=True)
    ot_t_an=models.CharField(max_length=100,blank=True)
    ot_c_an=models.CharField(max_length=100,blank=True)
    ot_t_ar=models.CharField(max_length=100,blank=True)
    ot_c_ar=models.CharField(max_length=100,blank=True)

class List_ProduitsProforma(models.Model):
    id_lp = models.AutoField(primary_key=True)
    collis =models.IntegerField(blank=True,null=True)
    poids=models.FloatField(null=True)
    prix_t=models.FloatField(null=True)
    id_p=models.ForeignKey(Produits,null=True)
    id_fa=models.ForeignKey(FacturesProforma,null=True)

class List_ProduitsEdex(models.Model):
    id_lp = models.AutoField(primary_key=True)
    collis =models.IntegerField(blank=True,null=True)
    poids=models.FloatField(null=True)
    prix_t=models.FloatField(null=True)
    id_p=models.ForeignKey(Produits,null=True)
    id_fa=models.ForeignKey(FacturesEdex,null=True)

class List_ProduitsUnpa(models.Model):
    id_lp = models.AutoField(primary_key=True)
    collis =models.IntegerField(blank=True,null=True)
    poids=models.FloatField(null=True)
    prix_t=models.FloatField(null=True)
    id_p=models.ForeignKey(Produits,null=True)
    id_fa=models.ForeignKey(FacturesUnpa,null=True)
