# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-02 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('IdCl', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_fr', models.CharField(default='', max_length=100)),
                ('Prenom_fr', models.CharField(default='', max_length=100)),
                ('Adresse_fr', models.CharField(default='', max_length=100)),
                ('Nom_an', models.CharField(default='', max_length=100)),
                ('Prenom_an', models.CharField(default='', max_length=100)),
                ('Adresse_an', models.CharField(default='', max_length=100)),
                ('Nom_ar', models.CharField(default='', max_length=100)),
                ('Prenom_ar', models.CharField(default='', max_length=100)),
                ('Adresse_ar', models.CharField(default='', max_length=100)),
                ('Numero', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(default=0, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('IdCB', models.AutoField(primary_key=True, serialize=False)),
                ('NumB_fr', models.CharField(default='', max_length=100)),
                ('NumB_an', models.CharField(default='', max_length=100)),
                ('NumB_ar', models.CharField(default='', max_length=100)),
                ('CodeS_fr', models.CharField(default='', max_length=100)),
                ('CodeS_an', models.CharField(default='', max_length=100)),
                ('CodeS_ar', models.CharField(default='', max_length=100)),
                ('AdresseB_fr', models.CharField(default='', max_length=100)),
                ('AdresseB_an', models.CharField(default='', max_length=100)),
                ('AdresseB_ar', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('IdFa', models.AutoField(primary_key=True, serialize=False)),
                ('PrixT', models.IntegerField(blank=True, default=0, null=True)),
                ('Destination', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ModeLivraison', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PortChargement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PaysOrigine', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('NbConteneur', models.IntegerField(blank=True, default=0, null=True)),
                ('NbColis', models.IntegerField(blank=True, default=0, null=True)),
                ('PoidsNet', models.IntegerField(blank=True, default=0, null=True)),
                ('PoidsBrut', models.IntegerField(blank=True, default=0, null=True)),
                ('NGP', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ModePaiement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('IdCBF', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.CompteBancaire')),
                ('IdClF', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='List_Produits',
            fields=[
                ('IdL', models.AutoField(primary_key=True, serialize=False)),
                ('Collis', models.IntegerField(default=0)),
                ('Poids', models.IntegerField(default=0)),
                ('IdFa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Factures')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('IdP', models.AutoField(primary_key=True, serialize=False)),
                ('Designation_fr', models.CharField(default='', max_length=100)),
                ('Designation_an', models.CharField(default='', max_length=100)),
                ('Designation_ar', models.CharField(default='', max_length=100)),
                ('prixU_fr', models.IntegerField(default=0)),
                ('prixU_an', models.IntegerField(default=0)),
                ('prixU_ar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='list_produits',
            name='IdP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Produits'),
        ),
        migrations.AddField(
            model_name='factures',
            name='IdPF',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Produits'),
        ),
    ]
