# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-02 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190802_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='IdCBF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CompteBancaire'),
        ),
    ]
