# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190802_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='IdCBF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CompteBancaire'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='IdClF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Clients'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='IdPF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Produits'),
        ),
    ]
