# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-05 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190804_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='id_p_f',
        ),
    ]
