# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-05 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_factures_id_p_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_produits',
            name='collis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='list_produits',
            name='poids',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
