# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190805_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='prix_t',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
