# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-05 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190805_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_produits',
            name='prix_t',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
