# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190807_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='destination',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='id_c_b_f',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CompteBancaire'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='id_c_f',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Clients'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='mode_livraison',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='mode_paiement',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='ngp',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='pays_origine',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='port_chargement',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
