# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-07 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190807_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='nb_colis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='nb_conteneur',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='poids_brut',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='poids_net',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='factures',
            name='prix_t',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
