# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190807_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_produits',
            name='collis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list_produits',
            name='poids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list_produits',
            name='prix_t',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
