# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-09 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190807_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
