# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-09 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_factures_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
