# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190809_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
