# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-18 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190809_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='produits',
            name='prix_u_an',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='produits',
            name='prix_u_ar',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='produits',
            name='prix_u_fr',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
