# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-18 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190818_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturesProforma',
            fields=[
                ('id_f', models.AutoField(primary_key=True, serialize=False)),
                ('prix_t', models.IntegerField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('mode_livraison', models.CharField(blank=True, max_length=100)),
                ('port_chargement', models.CharField(blank=True, max_length=100)),
                ('pays_origine', models.CharField(blank=True, max_length=100)),
                ('nb_conteneur', models.IntegerField(blank=True, null=True)),
                ('nb_colis', models.IntegerField(blank=True, null=True)),
                ('poids_net', models.DecimalField(decimal_places=3, max_digits=20)),
                ('poids_brut', models.DecimalField(decimal_places=3, max_digits=20)),
                ('ngp', models.CharField(blank=True, max_length=100)),
                ('mode_paiement', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('id_c_b_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CompteBancaire')),
                ('id_c_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='FacturesUnpa',
            fields=[
                ('id_f', models.AutoField(primary_key=True, serialize=False)),
                ('prix_t', models.IntegerField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('mode_livraison', models.CharField(blank=True, max_length=100)),
                ('port_chargement', models.CharField(blank=True, max_length=100)),
                ('pays_origine', models.CharField(blank=True, max_length=100)),
                ('nb_conteneur', models.IntegerField(blank=True, null=True)),
                ('nb_colis', models.IntegerField(blank=True, null=True)),
                ('poids_net', models.DecimalField(decimal_places=3, max_digits=20)),
                ('poids_brut', models.DecimalField(decimal_places=3, max_digits=20)),
                ('ngp', models.CharField(blank=True, max_length=100)),
                ('mode_paiement', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('id_c_b_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CompteBancaire')),
                ('id_c_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='List_ProduitsProforma',
            fields=[
                ('id_lp', models.AutoField(primary_key=True, serialize=False)),
                ('collis', models.IntegerField(blank=True, null=True)),
                ('poids', models.DecimalField(decimal_places=3, max_digits=20)),
                ('prix_t', models.IntegerField(blank=True, null=True)),
                ('id_fa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.FacturesProforma')),
                ('id_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Produits')),
            ],
        ),
        migrations.CreateModel(
            name='List_ProduitsUnpa',
            fields=[
                ('id_lp', models.AutoField(primary_key=True, serialize=False)),
                ('collis', models.IntegerField(blank=True, null=True)),
                ('poids', models.DecimalField(decimal_places=3, max_digits=20)),
                ('prix_t', models.IntegerField(blank=True, null=True)),
                ('id_fa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.FacturesUnpa')),
                ('id_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Produits')),
            ],
        ),
        migrations.RenameModel(
            old_name='Factures',
            new_name='FacturesEdex',
        ),
        migrations.RenameModel(
            old_name='List_Produits',
            new_name='List_ProduitsEdex',
        ),
    ]
