# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190819_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompteBancaire',
            new_name='CompteBancaires',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='prenom_an',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='prenom_ar',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='prenom_fr',
        ),
    ]
