# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190820_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturesedex',
            name='prix_t_lettres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesedex',
            name='unite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='prix_t_lettres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='unite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='prix_t_lettres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='unite',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
