# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190821_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturesedex',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
