# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190825_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_produitsedex',
            name='prix_t',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list_produitsproforma',
            name='prix_t',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list_produitsunpa',
            name='prix_t',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
