# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-02 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190902_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturesedex',
            name='prix_t',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturesproforma',
            name='prix_t',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturesunpa',
            name='prix_t',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
