# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-02 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20190902_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturesunpa',
            name='prix_t',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
