# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20190903_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturesedex',
            name='prix_t',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturesproforma',
            name='prix_t',
            field=models.FloatField(null=True),
        ),
    ]
