# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20190912_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturesedex',
            old_name='prix_t_lettres',
            new_name='prix_t_lettres_an',
        ),
        migrations.RenameField(
            model_name='facturesproforma',
            old_name='prix_t_lettres',
            new_name='prix_t_lettres_an',
        ),
        migrations.RenameField(
            model_name='facturesunpa',
            old_name='prix_t_lettres',
            new_name='prix_t_lettres_an',
        ),
        migrations.AddField(
            model_name='facturesedex',
            name='prix_t_lettres_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesedex',
            name='prix_t_lettres_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='prix_t_lettres_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='prix_t_lettres_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='prix_t_lettres_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='prix_t_lettres_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
