# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20190912_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturesedex',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
