# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-19 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20190912_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturesedex',
            name='ot_c_an',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesedex',
            name='ot_c_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesedex',
            name='ot_c_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesedex',
            name='ot_t_an',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesedex',
            name='ot_t_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesedex',
            name='ot_t_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='ot_c_an',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='ot_c_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='ot_c_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='ot_t_an',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='ot_t_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesproforma',
            name='ot_t_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='ot_c_an',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='ot_c_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='ot_c_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='ot_t_an',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='ot_t_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturesunpa',
            name='ot_t_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
