# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-07 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20191007_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturesedex',
            name='nb_conteneur',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturesunpa',
            name='nb_conteneur',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
